---
title: "MAGIC-BULLET"
format: html
---

## Press release from hei_INNOVATION

hei_INNOVATION announced that PD Dr. Andreas D. Meid started to work on MAGIC-BULLET on December 1, 2023. The pharmacist and biometrician was successful with the project for Heidelberg University at the Sanofi iDEA-iTECH Awards 2023. At the interface of pharmacometrics, he is working at the Heidelberg Medical Faculty on the development of a software platform for predicting the effectiveness of antibody-drug conjugates in cancer over several phases of clinical drug development.

Predicting therapeutic success on the basis of preclinical experiments is of great importance for drug development. This also applies to promising antibody drug conjugates (ADCs) in oncology. However, there have also been been numerous failures in clinical development. With the platform models being developed in the MAGIC-BULLET project, scientists can make well-founded decisions at important translation steps. For example, the model-based prediction of therapeutic success can support the development of lead structures or the planning of clinical trials and thus lead to shorter, more successful and more cost-effective development.

Dr. Andreas Meid explains: “If we assume that clinical progress can only be achieved through the interaction of basic research and clinical research, then all those aspects should be supported by mathematical-statistical models throughout these translational steps. The Sanofi funding initially makes it possible to research the underlying mechanisms from many already published experiments, from cell culture to clinical studies, and to integrate them into models. These models can then be tested and validated with available original patient data before model-informed decisions are derived from them. The Sanofi funding also offers the opportunity to pilot this with current data from drug development. In the long term, the platform models developed could therefore help to make future drug developments more successful.”

In a first step, the project will process the numerous models published to date and operationalize them in such a way that the behaviour of an ADC can be described and predicted in various studies. This platform model will then be further developed using ADCs in breast cancer therapy and validated with original data from clinical studies. Ultimately, the knowledge gained will be incorporated into a generically usable development platform and a guideline for future study planning.