project:
  type: website

website:
  title: "andreasmeid.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - test.qmd 
        text: Testseite
      #- href: https://andreas-d-meid.netlify.app/ 
      #  text: Academic Biography
  #sidebar

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



