project:
  type: website

website:
  title: "andreasmeid.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: projects.qmd 
        text: Projects
      - href: https://andreas-d-meid.netlify.app/ 
        text: Academic Biography
  sidebar:
  - id: projects
    title: "Projects Sidebar"
    style: "docked"
    background: light
    contents:
      - href: test.qmd 
        text: Testseite
      - section: Presentations
        #href: presentation/overview.qmd
        contents:
        - text: Example presentation
          href: presentation/Test_slides.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



