project:
  type: website  # This ensures you can render multiple formats like HTML or PDF

format:
  revealjs:
    self-contained: true  # Embed all resources into a single HTML file
    theme: simple          # Choose a theme (or use a custom one)
    css: styles.css        # Optional custom styles

output-file: index         # Render output as `index.html`